version: '3'

services:

  apache:
    container_name: realworld_apache
    build:
      context: .
      dockerfile: .docker/apache.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - sockets
    ports:
      - "8080:80"
    networks:
      - sockets-app-network

  sockets:
    container_name: realworld_sockets
    build:
      context: .
      dockerfile: .docker/sockets.dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "1667:1667"
      - "3000:3000"
    command: bash -c "deno run --allow-net --allow-read --unstable app.ts"
    networks:
      - sockets-app-network

networks:
  sockets-app-network:
    driver: bridge
